# Generated by Django 6.0.2 on 2026-02-21 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_any_user', 'Can view any user'), ('can_block_user', 'Can block user')],
                     'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
