# Generated by Django 6.0.2 on 2026-02-24 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_alter_user_groups_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_any_user', 'Может просматривать всех пользователей'),
                                     ('can_block_user', 'Может блокировать пользователей')],
                     'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
