# Generated by Django 6.0.2 on 2026-02-24 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_block_user', 'Может блокировать пользователей')],
                     'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
