# Generated by Django 6.0.2 on 2026-02-21 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sender', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_any_mailing', 'Can view any mailing'),
                                     ('can_disable_mailing', 'Can disable mailing')], 'verbose_name': 'Рассылка',
                     'verbose_name_plural': 'Рассылки'},
        ),
    ]
