# Generated by Django 6.0.2 on 2026-02-24 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sender', '0003_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('view_all_clients', 'Может просматривать любых клиентов')],
                     'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('view_all_messages', 'Может просматривать любые сообщения')],
                     'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
