# Generated by Django 6.0.2 on 2026-02-24 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sender', '0004_alter_client_options_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_any_mailing', 'Может просматривать любые рассылки'),
                                     ('can_disable_mailing', 'Может блокировать любые рассылки')],
                     'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
